version: "3.8"

networks:
  packwiz:
    external: true

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      PACKWIZ_URL: "http://172.22.0.1:8080/pack.toml"
      USE_AIKAR_FLAGS: true
      MEMORY: "6G"
      TYPE: "fabric"
      VERSION: "1.19.2"
    volumes:
      - ./data:/data
    networks:
      - packwiz
