name = "Pseudoscience Server Modpack"
author = "oskardotglobal, KhaosLatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "218bf3edb5c99a24af626799689275fb64f02bd5315ea963c7a034cc8ab604dd"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"
