name = "Pseudoscience Server Modpack"
author = "oskardotglobal, KhaosLatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4706d0859704a57e50fa19043576b911091dd96e0d3a4feb3393c30a07d4c9d"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"
