name = "Pseudoscience Modpack Iteration 0"
author = "oskardotglobal, KhaosLatet"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbf286720f3f08709478b69577ed3a097900e3f1e716a46de575287a692543ad"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
