name = "Pseudoscience Server Modpack"
author = "oskardotglobal, KhaosLatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d0db583f882c8f6c892cf2eb89260a519840a5d39da8e9fceb4f3b77bbada30"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"
