name = "Pseudoscience Server Modpack"
author = "oskardotglobal, KhaosLatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c80bdd73a4243ce52f7741c99de455bb9120e5d4f8e9d8c860a7743de2b25d85"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"
