name = "Pseudoscience Server Modpack"
author = "oskardotglobal, KhaosLatet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3034e78fe2b0c356d9cdfcd5b698a06b344e92f9501e68c1ed39bc98c5310aa6"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"
